### ISSUE TITLE
add preroll , endroll vast v3 on player

### ISSUE THREAD

**Issue by raisedhand** [hazycora/tv.hazy.su#3]
hi hazy , 
please add preroll , endroll vast v3 on player for make some money from traffic.

sample vast :
https://admin.deema.agency/?c=v&m=api&res=xml&placementId=1897&domain=wpaas.ir&page=index.php&cachebuster=45&wPlayer=640&hPlayer=480

if it's only need to set personal link like sample in env var config on heroku dyno , it's amazing & usefull.
waiting for your response
finest regards

**Comment by hazycora** [comment]
Sorry, I am not willing to add advertisement support to the site or to the repo.
Feel free to add this in a fork though! Do whatever you want with this project's source code. My repo will continue to be focused on having a privacy focused YouTube client with zero mandatory client-side javascript and zero advertisements.

The videos on the site aren't mine, they're made by all the creators on YouTube. Not having ads that pay _them_ is already hurtful, but I feel it's justified because advertisements on YouTube are designed to track users. Having my own ads on the site wouldn't feel fair, because although the code took work to create, _I did not create the videos on this site_ and I don't feel I should be paid when people view it, and I don't want to make it easier for others to profit directly from others viewing YouTuber's content so I won't add support for ads.

I wouldn't argue with you if you disagree though, and like I said you can do this in a fork if you want.

**Comment by raisedhand** [comment]
hello again ,
if i pay you , can you customize it for me to work with my vast ?
waiting for your response
